Repository RAF-SI-2023/Banka-3-Backend, pull requests merged in 2024-05, with the labels that each got.

#166 Izmene za modele hartija i jwt
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuySellStockCompanyDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyStockUserDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/enums/BankCertificate.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/enums/SellerCertificate.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/Contract.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyFuture.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  user-service/src/main/java/rs/edu/raf/userservice/util/jwt/JwtUtil.java
Labels: size/L, lgtm, approved

#159 Refactor tests implementation
  code-coverage/pom.xml
  email-service/src/test/java/com/example/emailservice/service/impl/EmployeeServiceUnitTest.java
  exchange-service/pom.xml
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/jacoco/ExcludeFromJacocoGeneratedReport.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/StockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/TickerServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/BuyStoksTests.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/BuyStoksTestsConfig.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/BuyStoksTestsSteps.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/BuyStockDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CardDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CardLoginDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CompanyAccountDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CreditRequestCreateDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CreditRequestDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/Currency.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/CurrencyExchangeDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/ProcessCreditRequestDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/StockDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/UserAccountDto.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/helper/WithdrawFundsDto.java
  user-service/src/test/resources/features/e2e/buyStok.feature
  user-service/src/test/resources/features/e2e/cardWithdraw.feature
  user-service/src/test/resources/features/e2e/credirRequest.feature
  user-service/src/test/resources/features/e2e/currencyExchangeService.feature
Labels: lgtm, approved, size/XXL

#171 [BCK-67]-Testiranje-OptionService-i-ContractService
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ContractServiceTests.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
Labels: size/L, lgtm, approved

#172 Dodani web socketi za front.
  exchange-service/pom.xml
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/SpringSecurityConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/StockUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/StockWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/WebSocketConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/MyStockServiceTest.java
Labels: size/L, lgtm, approved

#174 Sprint 7
  exchange-service/pom.xml
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/UserServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/SpringSecurityConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/StockUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/StockWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/WebSocketConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/CompanyAccountDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyStockCompanyDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/contract/ContractAnswerDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/Contract.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ContractServiceTests.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/userservice/service/CompanyService.java
  user-service/src/main/java/rs/edu/raf/userservice/service/EmployeeService.java
  user-service/src/main/java/rs/edu/raf/userservice/util/client/ExchangeServiceClient.java
Labels: lgtm, approved

#177 FutureContract dodat, izmene future-a da ima price
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureCompanyDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/listing/FutureDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Future.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/FutureContract.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/FutureContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/FutureContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
Labels: size/L, lgtm, approved

#179 BCK-64-OTC-Company-Stocks
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/M

#180 BCK-Bootstrap data
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  email-service/src/main/java/com/example/emailservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XL

#181 Revert "BCK-Bootstrap data (#180)"
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  email-service/src/main/java/com/example/emailservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XL

#183 Sprint 7 otc korisnici v.2
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/StockTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/repository/CompanyAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/repository/UserAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/MakePublicStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/StockOrderDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/BankTransactionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureCompanyDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuySellStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyStockUserOTCDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/FutureContract.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyFuture.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/FutureOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/FutureOrderSell.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrderSell.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/FutureContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/FutureRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyFutureRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/FutureOrderRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/FutureContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ContractServiceTests.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/XXL

#195 Sprint 7 Final
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/StockTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/repository/CompanyAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/repository/UserAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/MakePublicStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/StockOrderDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/BankTransactionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureCompanyDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyFutureDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuySellStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyStockUserOTCDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/listing/FutureDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Future.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/FutureContract.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyFuture.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/FutureOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/FutureOrderSell.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrderSell.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/FutureContractRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/FutureRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyFutureRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/FutureOrderRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/FutureContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ContractServiceTests.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/XXL

#196 BCK-69 Profit menjacnice
  bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
  bank-service/src/main/java/com/example/bankservice/domain/model/CommissionFromCurrencyExchange.java
  bank-service/src/main/java/com/example/bankservice/repository/CommissionFromCurrencyExhangeRepository.java
  bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
  bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
Labels: size/L, lgtm, approved

#197 Revert "BCK-69 Profit menjacnice (#196)"
  bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
  bank-service/src/main/java/com/example/bankservice/domain/model/CommissionFromCurrencyExchange.java
  bank-service/src/main/java/com/example/bankservice/repository/CommissionFromCurrencyExhangeRepository.java
  bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
  bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
Labels: size/L, lgtm, approved

#198 Bck 69 profit menjacnice
  bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
  bank-service/src/main/java/com/example/bankservice/domain/model/CommissionFromCurrencyExchange.java
  bank-service/src/main/java/com/example/bankservice/repository/CommissionFromCurrencyExhangeRepository.java
  bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
  bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
Labels: size/L, lgtm, approved

#199 Implementacija MongoDB-a za Email service
  email-service/pom.xml
  email-service/src/main/java/com/example/emailservice/domain/model/CompanyActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/EmployeeActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/PasswordReset.java
  email-service/src/main/java/com/example/emailservice/domain/model/TransactionActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/UserActivation.java
  email-service/src/main/java/com/example/emailservice/repository/CompanyActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/EmployeeActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/PasswordResetRepository.java
  email-service/src/main/java/com/example/emailservice/repository/TransactionActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/UserActivationRepository.java
  email-service/src/main/resources/application.properties
Labels: lgtm, approved, size/M

#200 Update application.properties
  email-service/src/main/resources/application.properties
Labels: lgtm, approved, size/XS

#201 [BCK-67] Implementacija Redis Za User Service
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/UserServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/userservice/UserServiceApplication.java
  user-service/src/main/java/rs/edu/raf/userservice/configuration/RedisCacheConfig.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/CompanyController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/ContactController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/PermissionController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/RoleController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/UserController.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/contact/ContactDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/employee/EmployeeDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/employee/ExchangeEmployeeDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/user/UserDto.java
  user-service/src/main/resources/application.properties
Labels: size/L, lgtm, approved

#202 Sprint 8 url za mongo
  email-service/src/main/resources/application.properties
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
Labels: lgtm, approved

#203 Bck 73 skidanje para otc
  bank-service/src/main/java/com/example/bankservice/configuration/SpringSecurityConfig.java
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/CompanyOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/UserOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/model/enums/TransactionType.java
  bank-service/src/main/java/com/example/bankservice/repository/CompanyAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/repository/UserAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/CompanyController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/UserController.java
Labels: size/L, lgtm, approved

#204 Sprint 8
  bank-service/src/main/java/com/example/bankservice/configuration/SpringSecurityConfig.java
  bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/CompanyOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/UserOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/model/CommissionFromCurrencyExchange.java
  bank-service/src/main/java/com/example/bankservice/domain/model/enums/TransactionType.java
  bank-service/src/main/java/com/example/bankservice/repository/CommissionFromCurrencyExhangeRepository.java
  bank-service/src/main/java/com/example/bankservice/repository/CompanyAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/repository/UserAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
  bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
  email-service/pom.xml
  email-service/src/main/java/com/example/emailservice/domain/model/CompanyActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/EmployeeActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/PasswordReset.java
  email-service/src/main/java/com/example/emailservice/domain/model/TransactionActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/UserActivation.java
  email-service/src/main/java/com/example/emailservice/repository/CompanyActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/EmployeeActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/PasswordResetRepository.java
  email-service/src/main/java/com/example/emailservice/repository/TransactionActivationRepository.java
  email-service/src/main/java/com/example/emailservice/repository/UserActivationRepository.java
  email-service/src/main/resources/application.properties
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/UserServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/userservice/UserServiceApplication.java
  user-service/src/main/java/rs/edu/raf/userservice/configuration/RedisCacheConfig.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/CompanyController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/ContactController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/PermissionController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/RoleController.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/UserController.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/contact/ContactDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/employee/EmployeeDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/employee/ExchangeEmployeeDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/dto/user/UserDto.java
  user-service/src/main/resources/application.properties
Labels: lgtm, approved, size/XL

#205 dodate 2 firme, jedan user i bootstrap data za exchangeService
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ExchangeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/ForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/bootstrap
Labels: lgtm, approved, size/XL

#207 Sprint 9
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/model/User.java
Labels: lgtm, approved, size/XS

#208 dodati porez, profit, i kupovina forexa
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ActuaryController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ForexController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/TaxController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/CompanyOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/UserOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyForexDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/ProfitStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/TaxStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyForex.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/ForexOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ProfitStockRepositorty.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/TaxStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/ForexRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyForexRepositroy.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/ForexOrderRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/TaxService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/TickerServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/model/Company.java
Labels: lgtm, approved, size/XL
