Repository RAF-SI-2023/Banka-3-Backend, pull requests merged in 2024-04, with the labels that each got.

#111 Pomozi boze
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/dto/creditrequest/CreditRequestDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/model/enums/CurrencyName.java
Labels: size/L, lgtm

#114 Jacoco implementation
  bank-service/pom.xml
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  code-coverage/pom.xml
  code-coverage/src/main/java/rs/edu/raf/Main.java
  email-service/pom.xml
  exchange-service/pom.xml
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ExchangeServiceApplicationTests.java
  pom.xml
  user-service/pom.xml
  user-service/src/test/java/rs/edu/raf/userservice/services/CompanyServiceTest.java
  user-service/src/test/java/rs/edu/raf/userservice/services/ContactServiceUnitTests.java
  user-service/src/test/java/rs/edu/raf/userservice/services/CustomDetailsServiceTest.java
Labels: size/XL

#124 Spirnt 4 exchange
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/ExchangeServiceApplication.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/SwaggerConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ActuaryController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ForexController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/FutureController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/HistoryController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/SellStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/mappers/StockMapper.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/Exchange.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/helper/CallsOptions.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/helper/GlobalQuote.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/helper/Result.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Forex.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Future.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Option.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Stock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Ticker.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyFuture.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyOption.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListings/MyFuture.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListings/MyOption.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/FutureOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/OptionOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/StockOrderSell.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ActuaryRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ExchangeRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/TickerRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/ForexRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/FutureRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/OptionRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/StockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/TickerRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/StockOrderRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/StockOrderSellRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ExchangeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockDailyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockIntradayService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockMonthlyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockWeeklyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/ForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/StockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingsService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/main/resources/data/exchange_data.csv
Labels: size/XXL

#126 [BCK-53] Dodati podrsku za kartice
  bank-service/src/main/java/com/example/bankservice/controller/CardController.java
  bank-service/src/main/java/com/example/bankservice/domains/dto/CardDto.java
  bank-service/src/main/java/com/example/bankservice/domains/dto/CreateCardDto.java
  bank-service/src/main/java/com/example/bankservice/domains/mappers/CardMapper.java
  bank-service/src/main/java/com/example/bankservice/domains/model/Card.java
  bank-service/src/main/java/com/example/bankservice/repositories/CardRepository.java
  bank-service/src/main/java/com/example/bankservice/services/CardService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ATMController.java
  user-service/src/main/java/rs/edu/raf/userservice/controllers/CreateCardDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/dto/card/CreateCardDto.java
  user-service/src/main/java/rs/edu/raf/userservice/services/AccountService.java
  user-service/src/main/java/rs/edu/raf/userservice/utils/BankServiceClient.java
Labels: size/L, lgtm

#128 BCK-52 Dodavanje objekata u bootstrapData
  bank-service/src/main/java/com/example/bankservice/repositories/CardRepository.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
Labels: size/L, lgtm

#132 premesteno iz bank u user service i dodate withdraw/deposit/cardlogin…
  user-service/src/main/java/rs/edu/raf/userservice/controllers/CardController.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/dto/card/CardDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/dto/card/CardResponseDto.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/mappers/CardMapper.java
  user-service/src/main/java/rs/edu/raf/userservice/domains/model/Card.java
  user-service/src/main/java/rs/edu/raf/userservice/repositories/CardRepository.java
  user-service/src/main/java/rs/edu/raf/userservice/services/CardService.java
Labels: size/L, lgtm

#138 Kolokvijumska
  user-service/src/main/resources/application.properties
  user-service/src/test/java/rs/edu/raf/userservice/integration/contactController/ContactControllerTestSteps.java
  user-service/src/test/java/rs/edu/raf/userservice/integration/contactController/ContactControllerTests.java
  user-service/src/test/java/rs/edu/raf/userservice/integration/contactController/ContactControllerTestsConfig.java
  user-service/src/test/java/rs/edu/raf/userservice/integration/contactController/ContactControllerTestsState.java
  user-service/src/test/java/rs/edu/raf/userservice/services/UserServiceApplicationTests.java
  user-service/src/test/resources/features/integration/contactController.feature
Labels: size/L

#141 Add basic CI
  .github/CODEOWNERS
  .github/workflows/pr-ci.yaml
Labels: lgtm, size/M

#146 Testiranje dare
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/CardServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/CreditRequestServiceUnitTest.java
Labels: size/XL

#150 Finished CI
  .prow/bank-service.yaml
  .prow/build.yaml
  .prow/email-service.yaml
  .prow/exchange-service.yaml
  .prow/user-service.yaml
  OWNERS
Labels: size/L

#154 Added transaction fix
  .prow/bank-service.yaml
  .prow/build.yaml
  .prow/email-service.yaml
  .prow/exchange-service.yaml
  .prow/user-service.yaml
  email-service/src/main/java/com/example/emailservice/repository/TransactionActivationRepository.java
  email-service/src/main/java/com/example/emailservice/service/TransactionService.java
Labels: size/L, lgtm, approved

#158 Fix-prow
  .prow/exchange-service.yaml
Labels: size/L, lgtm, approved
