Repository RAF-SI-2023/Banka-3-Backend, pull requests merged in 2024-06, with the labels that each got.

#210 Sprint 9
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ActuaryController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ForexController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/TaxController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/CompanyOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/UserOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyForexDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/ProfitStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/TaxStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyForex.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/order/ForexOrder.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/ProfitStockRepositorty.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/TaxStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/ForexRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyForexRepositroy.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/orderRepository/ForexOrderRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ExchangeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/TaxService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/ForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/TickerServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/model/Company.java
  user-service/src/main/java/rs/edu/raf/userservice/domain/model/User.java
  user-service/src/main/resources/bootstrap
Labels: lgtm, approved, size/XXL

#211 Add helm deployment
  .prow/build.yaml
Labels: size/XS

#212 Bck 68 implementacija otc trgovine sa bankom 4
  exchange-service/pom.xml
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/ExchangeServiceApplication.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/FrontendOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyStockDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/OfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/listing/Bank4Stock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/MyOffer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/Offer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/OfferStatus.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/Bank4StockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/offerRepository/MyOfferRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/offerRepository/OfferRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
Labels: lgtm, approved, size/XL

#213 Otc banaka tests
  bank-service/src/main/java/com/example/bankservice/service/CommissionFromCurrencyExchangeService.java
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockDailyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockIntradayService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockMonthlyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/historyService/StockWeeklyService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ActuaryServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/Banka4OtcServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ContractServiceTests.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/ExchangeServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/FutureContractServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/TaxServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/historyService/StockDailyServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/historyService/StockIntradayServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/historyService/StockMonthlyServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/historyService/StockWeeklyServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/ForexServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/StockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyForexServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/XXL

#214 Set-pop
  email-service/src/main/java/com/example/emailservice/configuration/EmailConfig.java
  email-service/src/main/resources/application.properties
Labels: lgtm, approved

#215 Update mail config
  email-service/src/main/java/com/example/emailservice/configuration/EmailConfig.java
  email-service/src/main/resources/application.properties
Labels: size/XS

#216 Check balance implementation
  bank-service/src/main/java/com/example/bankservice/controller/AccountController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/account/CheckAccountBalanceDto.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  email-service/src/main/java/com/example/emailservice/bootstrap/BootstrapData.java
  email-service/src/main/java/com/example/emailservice/domain/model/CompanyActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/EmployeeActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/PasswordReset.java
  email-service/src/main/java/com/example/emailservice/domain/model/TransactionActivation.java
  email-service/src/main/java/com/example/emailservice/domain/model/UserActivation.java
  email-service/src/main/java/com/example/emailservice/service/mongo/MongoService.java
  email-service/src/test/java/com/example/emailservice/service/impl/CompanyServiceTest.java
  email-service/src/test/java/com/example/emailservice/service/impl/TransactionServiceTest.java
Labels: size/L, lgtm, approved

#218 websocket update kidalica
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/SpringSecurityConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/WebSocketConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/contract/ContractUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/contract/ContractWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/forex/ForexUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/forex/ForexWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/future/FutureUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/future/FutureWebSockettHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyForexService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyForexServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockServiceTest.java
Labels: size/L, lgtm, approved

#219 NADZORNI ORGAN OGNJEN UVIDEO GRESKU I JA JE ISPRAVIO
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/WebSocketConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/forex/ForexWebSocketHandler.java
Labels: size/S, lgtm, approved

#220 Bck kupovina i prodaja opcija
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/BuyOptionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/BuyOptionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/buySell/SellOptionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyOption.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/OptionRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyOptionRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
Labels: size/L, lgtm, approved

#221 janko i damir sitnicare u kasne sate
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/service/CreditRequestService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/CreditRequestServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/bootstrap/BootstrapData.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ExchangeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
  user-service/src/main/resources/bootstrap
Labels: lgtm, approved, size/XL

#222 Sitne ispravke
  bank-service/src/main/java/com/example/bankservice/repository/TransactionRepository.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  email-service/src/main/java/com/example/emailservice/service/EmployeeService.java
  email-service/src/main/java/com/example/emailservice/service/UserService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ContractController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/FutureContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
Labels: lgtm, approved

#225 dodato oporezivanja, i jos neke izmene
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/CompanyOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/StockTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/UserOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/model/enums/TransactionType.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ForexController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/BankTransactionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/CompanyOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/UserOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
Labels: size/L, lgtm, approved

#226 dodate neke izmene
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/OfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/Offer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/Bank4StockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/Banka4OtcServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
Labels: size/L, lgtm, approved

#227 dodati soketi za myOption i geter
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyOption.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyOptionRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
Labels: lgtm, approved

#228 odradjen email service
  email-service/pom.xml
  email-service/src/main/java/com/example/emailservice/service/email/EmailServiceImplementation.java
  email-service/src/main/resources/application.properties
  email-service/src/test/java/com/example/emailservice/service/impl/EmailServiceImplementationTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
Labels: lgtm, approved, size/M

#229 Otc banka4 izmene konacne
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/FrontendOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/MyOffer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/Banka4OtcServiceTest.java
Labels: size/S, lgtm, approved

#230 izmene za ogija
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/MyOffer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
Labels: size/S, lgtm, approved

#232 Uradjeni svi testovi
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  email-service/pom.xml
  email-service/src/main/java/com/example/emailservice/jacoco/ExcludeFromJacocoGeneratedReport.java
  email-service/src/main/java/com/example/emailservice/service/email/EmailServiceImplementation.java
  email-service/src/main/java/com/example/emailservice/service/mongo/MongoService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/Banka4OtcServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/XXL

#233 izmenjeni linkovi i actuary service
  email-service/src/main/java/com/example/emailservice/service/EmployeeService.java
  email-service/src/main/java/com/example/emailservice/service/UserService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
Labels: lgtm, approved, size/XS

#234 Kt 5
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/CompanyOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/StockTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/UserOtcTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/model/enums/TransactionType.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  email-service/pom.xml
  email-service/src/main/java/com/example/emailservice/jacoco/ExcludeFromJacocoGeneratedReport.java
  email-service/src/main/java/com/example/emailservice/service/EmployeeService.java
  email-service/src/main/java/com/example/emailservice/service/UserService.java
  email-service/src/main/java/com/example/emailservice/service/email/EmailServiceImplementation.java
  email-service/src/main/java/com/example/emailservice/service/mongo/MongoService.java
  email-service/src/main/resources/application.properties
  email-service/src/test/java/com/example/emailservice/service/impl/EmailServiceImplementationTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/Banka4OtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/ForexController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/OptionController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/BankTransactionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/CompanyOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/UserOtcDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/FrontendOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/MyOfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/offer/OfferDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyOption.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/MyOffer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/offer/Offer.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/listingRepository/Bank4StockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyOptionRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ActuaryService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/Banka4OtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/FutureService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/OptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/Banka4OtcServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/listingService/OptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyOptionServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/FuturOrderServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XXL

#237 Otc banaka
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/BankOtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/XS

#238 dodata ruta za birsanje offera
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/BankOtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/M

#239 Otc janko
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/BankOtcController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/M

#241 banka 4 OTC
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/XS

#242 dodat deo za marzne racune u exchange servisu i za menjcacnicu geteri
  bank-service/src/main/java/com/example/bankservice/controller/CurrencyExchangeController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/currencyExchange/CommissionByMarkDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/currencyExchange/CommissionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/model/CurrencyExchange.java
  bank-service/src/main/java/com/example/bankservice/service/CurrencyExchangeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/client/BankServiceClient.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/controller/StockController.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/dto/bank/BankMarginTransactionDto.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/TaxStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/domain/model/myListing/MyMarginStock.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/repository/myListingRepository/MyMarginStockRepository.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/TaxService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyMarginStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/TaxServiceTest.java
Labels: size/L, lgtm, approved

#243 Marzni racuni za Bank Service
  bank-service/src/main/java/com/example/bankservice/controller/AccountController.java
  bank-service/src/main/java/com/example/bankservice/controller/CompanyAccountController.java
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/account/UserMarginAccountCreateDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/account/UserMarginAccountDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/companyaccount/CompanyMarginAccountCreateDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/companyaccount/CompanyMarginAccountDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/AddToMarginDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/MarginTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/StockMarginTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/WithdrawFromMarginDto.java
  bank-service/src/main/java/com/example/bankservice/domain/mapper/CompanyAccountMapper.java
  bank-service/src/main/java/com/example/bankservice/domain/mapper/TransactionMapper.java
  bank-service/src/main/java/com/example/bankservice/domain/mapper/UserAccountMapper.java
  bank-service/src/main/java/com/example/bankservice/domain/model/enums/TransactionType.java
  bank-service/src/main/java/com/example/bankservice/domain/model/marginAccounts/CompanyMarginAccount.java
  bank-service/src/main/java/com/example/bankservice/domain/model/marginAccounts/MarginAccount.java
  bank-service/src/main/java/com/example/bankservice/domain/model/marginAccounts/UserMarginAccount.java
  bank-service/src/main/java/com/example/bankservice/repository/MarginAccountRepository.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
Labels: lgtm, approved, size/XL

#244 banka 1
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/XS

#245 Finale otc bank1
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
Labels: lgtm, approved, size/XS

#247 funkcionalnost oko tickera i ispravljeni marzni racuni
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/MarginTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/listingService/TickerService.java
Labels: size/L, lgtm, approved

#250 email service URL-ovi
  email-service/src/main/java/com/example/emailservice/service/EmployeeService.java
  email-service/src/main/java/com/example/emailservice/service/UserService.java
Labels: lgtm, approved, size/XS

#251 dodate izmene za marzne racune
  bank-service/src/main/java/com/example/bankservice/bootstrap/BootstrapData.java
  bank-service/src/main/java/com/example/bankservice/domain/model/marginAccounts/MarginAccount.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
Labels: size/L, lgtm, approved

#252 promenjena ruta ka getallMartginTransactions
  bank-service/src/main/java/com/example/bankservice/controller/TransactionController.java
  bank-service/src/main/java/com/example/bankservice/domain/dto/transaction/MarginTransactionDto.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
Labels: size/S, lgtm, approved

#246 Monitoring
  bank-service/pom.xml
  bank-service/src/main/java/com/example/bankservice/configuration/MetricsConfig.java
  bank-service/src/main/java/com/example/bankservice/configuration/SpringSecurityConfig.java
  bank-service/src/main/java/com/example/bankservice/controller/AccountController.java
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/resources/application.properties
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  email-service/pom.xml
  exchange-service/pom.xml
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/userservice/configuration/MetricsConfig.java
  user-service/src/main/java/rs/edu/raf/userservice/configuration/SpringSecurityConfig.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/ContactController.java
  user-service/src/main/java/rs/edu/raf/userservice/service/ContactService.java
  user-service/src/main/resources/application.properties
  user-service/src/test/java/rs/edu/raf/userservice/services/ContactServiceUnitTests.java
Labels: size/L, lgtm, approved

#254 Update exchange-service.yaml
  .prow/exchange-service.yaml
Labels: lgtm, approved, size/XS

#255 Napisani testovi i sredjen coverage
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/AccountServiceUnitTest.java
  bank-service/src/test/java/com/example/bankservice/CurrencyExchangeServiceTest.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/BankOtcServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyMarginStockServiceTest.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderServiceTest.java
Labels: lgtm, approved, size/XXL

#257 izmene otc korisnika, loan vrednost
  bank-service/src/main/java/com/example/bankservice/service/AccountService.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  email-service/src/main/java/com/example/emailservice/service/email/EmailServiceImplementation.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/StockWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/contract/ContractWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/forex/ForexWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/future/FutureWebSockettHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/option/OptionWebSocketHandler.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/orderService/StockOrderService.java
  user-service/src/test/java/rs/edu/raf/userservice/e2e/byStoks/BuyStoksTestsSteps.java
  user-service/src/test/java/rs/edu/raf/userservice/integration/employeeController/EmployeeControllerTestSteps.java
Labels: lgtm, approved, size/M
