Repository RAF-SI-2023/Banka-3-Backend, pull requests merged in 2024-07, with the labels that each got.

#258 margin web socket
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/SpringSecurityConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/WebSocketConfig.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/margin/MarginUpdateEvent.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/configuration/margin/MarginWebSocketHandler.java
Labels: lgtm, approved, size/M

#259 ispraljen login zaposlenog, i marzni racuni
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  email-service/src/main/java/com/example/emailservice/service/EmployeeService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/ContractService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyMarginStockService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/service/myListingService/MyMarginStockServiceTest.java
  user-service/src/main/java/rs/edu/raf/userservice/controller/EmployeeController.java
  user-service/src/main/java/rs/edu/raf/userservice/service/EmployeeService.java
Labels: lgtm, approved, size/M

#260 ispravke
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyStockService.java
Labels: size/L, lgtm, approved

#261 Unit testovi, zavrsen coverage
  bank-service/src/main/java/com/example/bankservice/jacoco/ExcludeFromJacocoGeneratedReport.java
  bank-service/src/main/java/com/example/bankservice/service/TransactionService.java
  bank-service/src/test/java/com/example/bankservice/TransactionServiceTest.java
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/BankOtcService.java
  exchange-service/src/test/java/rs/edu/raf/exchangeservice/BankOtcServiceTest.java
Labels: size/L, lgtm, approved

#262 web socket za future
  exchange-service/src/main/java/rs/edu/raf/exchangeservice/service/myListingService/MyFutureSerivce.java
Labels: lgtm, approved, size/XS

#263 Update README.md
  README.md
Labels: lgtm, approved, size/XS
